### ISSUE TITLE
RINEX OBS Header "LEAP SECONDS"

### ISSUE THREAD

**Issue by markusbradke** [wlcable/GeoStar_GNSS_Bin2RINEX#2]
Not sure what numbers 2 to 4 refer to in line "    18    18   137     7                                    LEAP SECONDS"

The second "18" you only need if your file is in future, the "137" should be the GPS week, in that case "2140" and "7" is the day, in that case "1".

You can skip these values since they are optional though.

**Comment by wlcable** [comment]
This is all just copied from the original program from GeoStar and these values come directly from the 0x1D Message (GPS Time to UTC Conversion Parameters), unmodified.
2 - utc.dtlsf (Word 8:bit15-0) - Future leap second count Δ t LSF
3 - utc.wnlsf (Word 7:bit15-0) - Future leap second reference Week Number WN LSF
4 - utc.dn (Word 7:bit31-16) - Leap second reference Day Number DN
Here is a snip from the Bin protocol for this message.
![image](https://user-images.githubusercontent.com/50362808/104732143-10b74580-573d-11eb-8cad-6862f08c573e.png)
I think there must be an error in the firmware and it sends / calculates the wrong values.
I will probably just remove the extra values in the next version since, as you mention, they are optional.

**Comment by markusbradke** [comment]
Header label is ok now
